### PR TITLE
Release 0.3.0

### PR DESCRIPTION
**Pull request by etingof**

### CODE REVIEW

**Comment by etingof** [comment]
@sydneyli Could you please take a look at CHANGES - did we forget to note anything significant?

**Comment by sydneyli** [comment]
This looks good to me. Maybe a mention of the new Sphinx documentation?

**Comment by etingof** [comment]
Added a note, though the docs are not there yet.

**Comment by etingof** [comment]
https://pypi.org/project/apacheconfig/0.3.0/

**Pull request merged**
